--- # Playbooks - DelegateTo
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet client
      yum: pkg=telnet state=latest
      delegate_to: 127.0.0.1
