--- # Fetch Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Download remote folder
      fetch: src=/etc/hosts dest=/home/ansible/prefix-{{ ansible_hostname }} flat=yes
