--- # GetURL Module
- hosts: apacheweb
  user: ansible 
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Get and download the INI file from the web server
      get_url: url=http://proof.ovh.net/files/100Mb.dat dest=/home/ansible/mytest.ini mode=0440
