--- # HTPasswd Module
- hosts: ubuntu 
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Python-passlib
      apt: name=python-passlib state=latest
    - name: Adding user to web site authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test2 password=qwerty123 state=present 
