--- # MYSQL_DB MODULE DEMO

- hosts: ubuntu
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install the Python-pip
      apt: pkg=python-pip state=latest
    - name: Install the Python MySQL Support Libraries
      shell: apt-get install python-dev libmysqlclient-dev -y
    - name: Install the Python MySQL Support Libraries (2)
      shell: pip install MySQL-python
    - name: Create a New Test DB called MyNewDB
      mysql_db: name=MyNewDB state=present login_user=root login_password=f349fmk3g53g3
