--- # Notufy Playbook
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Apache
      action: yum name=httpd state=installed update_cache=true
      notify: Restart Apache
  handlers:
    - name: Restart Apache
      action: service name=httpd state=restarted
