--- # Prompt Playbook
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:  
    playbook_version: 0.01b
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install which packet
      default: telnet
      private: no
  tasks:
    - name: Install {{ pkgtoinstall }} 
      yum: pkg={{ pkgtoinstall }} state=latest
