--- # Shell Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Remote command 
      shell: /usr/bin/uptime >> uptime.log
      args:
        chdir: logs/
        creates: uptime.log
