--- # Stat Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - stat: path=/home/ansible/abc
      register: res
    - debug: msg="The path exist and is Direcroty"
      when: res.stat.isdir is defined and res.stat.isdir
