--- # Playbook with tags
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Install telnet and lynx
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: Verify that telnet is installed
      raw: yum list installed | grep telnet > /home/ansible/pkg.log
      tags:
        - logging
