--- # Using templates
- hosts: 127.0.0.1
  connection: local
  user: ansible
  sudo: yes
  gather_facts: yes
  vars:
    userName: ansible
    userPassword: strongpasswodr123
    connectionType: SFTP
  tasks:
    - name: Install the config file customized for the system
      template: src=test.conf.j2 dest=/home/ansible/test.conf owner=ansible group=ansible mode=750

