--- # Master playbook for Role based NFS server deployment

- hosts: appserver
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When did the role start
    raw: date > /home/ansible/startofrole.log
  roles:
    - nfs.server
  post_tasks:
  - name: When did the role finish
    raw: date > /home/ansible/endofrole.log
