--- # Master playbook for Role based apache web deployment

- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When did the role start
    raw: date > /home/ansible/startofrole.log
  roles:
    - redhat.apachewebserver
  post_tasks:
  - name: When did the role finish
    raw: date > /home/ansible/endofrole.log
